//! Regenerate Tests/PureVectors.lean with:
//! cargo run --locked --release --example pure_vectors > ../Tests/PureVectors.lean
//!
//! The output is one `Blake3.PureTests.Vectors` literal; the schema lives in
//! Tests/Vectors.lean. Only literals are emitted, so the generator needs no
//! knowledge of Lean beyond field names and brackets.

use std::fmt::Write;

use blake3::hazmat::{HasherExt, Mode, merge_subtrees_non_root, merge_subtrees_root};

fn input(length: usize, salt: usize) -> Vec<u8> {
    (0..length)
        .map(|i| u8::try_from((i * 17 + i / 251 * 13 + salt * 29) % 256).unwrap())
        .collect()
}

fn hex(bytes: &[u8; 32]) -> String {
    bytes.iter().fold(String::with_capacity(64), |mut out, byte| {
        write!(out, "{byte:02x}").unwrap();
        out
    })
}

fn main() {
    println!("/- Generated by rust/examples/pure_vectors.rs. Do not edit. -/");
    println!("import Tests.Vectors");
    println!();
    println!("def Blake3.PureTests.vectors : Blake3.PureTests.Vectors := {{");
    println!("  reference := \"1.8.7\",");
    println!("  chunks := [");
    let counters = [
        0,
        1,
        2,
        255,
        (1_u64 << 32) - 1,
        1_u64 << 32,
        (1_u64 << 54) - 1,
    ];
    for counter in counters {
        for length in [1, 63, 64, 65, 1023, 1024] {
            let data = input(length, usize::try_from(counter % 251).unwrap());
            let cv = blake3::Hasher::new()
                .set_input_offset(counter * 1024)
                .update(&data)
                .finalize_non_root();
            let cv = hex(&cv);
            println!("    {{ counter := {counter}, length := {length}, cv := \"{cv}\" }},");
        }
    }
    println!("  ],");
    println!("  parents := [");
    for salt in 0..64 {
        let left: [u8; 32] = input(32, salt).try_into().unwrap();
        let right: [u8; 32] = input(32, salt + 83).try_into().unwrap();
        let cv = hex(&merge_subtrees_non_root(&left, &right, Mode::Hash));
        let root = hex(merge_subtrees_root(&left, &right, Mode::Hash).as_bytes());
        let ordinary = hex(blake3::hash(&[left, right].concat()).as_bytes());
        println!("    {{ salt := {salt}, cv := \"{cv}\", root := \"{root}\", ordinary := \"{ordinary}\" }},");
    }
    println!("  ],");
    println!("}}");
}
