//! Regenerate Tests/PureVectors.lean with:
//! cargo run --locked --release --example pure_vectors > ../Tests/PureVectors.lean

use blake3::hazmat::{HasherExt, Mode, merge_subtrees_non_root, merge_subtrees_root};

fn input(length: usize, salt: usize) -> Vec<u8> {
    (0..length)
        .map(|i| u8::try_from((i * 17 + i / 251 * 13 + salt * 29) % 256).unwrap())
        .collect()
}

fn main() {
    println!("/- Generated by rust/examples/pure_vectors.rs using BLAKE3 1.8.7. -/");
    println!("namespace Blake3.PureTests\n");
    println!("def chunkVectors : List (Nat × Nat × List UInt8) := [");
    let counters = [
        0,
        1,
        2,
        255,
        (1_u64 << 32) - 1,
        1_u64 << 32,
        (1_u64 << 54) - 1,
    ];
    for (index, counter) in counters.into_iter().enumerate() {
        for (part, length) in [1, 63, 64, 65, 1023, 1024].into_iter().enumerate() {
            let data = input(length, usize::try_from(counter % 251).unwrap());
            let cv = blake3::Hasher::new()
                .set_input_offset(counter * 1024)
                .update(&data)
                .finalize_non_root();
            let separator = if index == 6 && part == 5 { "]" } else { "," };
            println!("  ({counter}, {length}, {cv:?}){separator}");
        }
    }
    println!("\ndef parentVectors : List (List UInt8 × List UInt8 × List UInt8) := [");
    for salt in 0..64 {
        let left: [u8; 32] = input(32, salt).try_into().unwrap();
        let right: [u8; 32] = input(32, salt + 83).try_into().unwrap();
        let cv = merge_subtrees_non_root(&left, &right, Mode::Hash);
        let root = *merge_subtrees_root(&left, &right, Mode::Hash).as_bytes();
        let ordinary = *blake3::hash(&[left, right].concat()).as_bytes();
        let separator = if salt == 63 { "]" } else { "," };
        println!("  ({cv:?}, {root:?}, {ordinary:?}){separator}");
    }
    println!("\nend Blake3.PureTests");
}
